version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mypod
      POSTGRES_PASSWORD: "2qBi9o2Bhvv7U3YgeN1dItQpxL1izTBR"
    volumes:
      - mypod_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
volumes:
  mypod_data: