name: bofa_enhanced
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  postgres: ^3.5.1
  dart_jsonwebtoken: ^2.0.0
  mailer: ^6.0.1
  random_string: ^2.3.1
  http: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  shelf_router_generator: ^1.1.0
  build_runner: ^2.4.13
